name: Docker Publish

on: workflow_dispatch

concurrency:
  group: docker-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ENV_FILE: .env
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
      - name: Load environment variables from .env file
        id: import-env
        shell: bash
        run: |
          while read line; do
             if [[ $line =~ ^#.*$ ]] || [[ -z $line ]]; then
              continue
            fi
            echo "$line" >> $GITHUB_ENV
          done < ${{ env.ENV_FILE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # github.actor is the username of the user who triggered the workflow. Alternative: github.repository_owner
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata for PHP
        id: meta-php
        uses: docker/metadata-action@v4
        with:
          labels: |
            org.opencontainers.image.description=Docker image for PHP
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-php
      - name: Build and push image for PHP
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: tools/docker/php-fpm/build.Dockerfile
          build-args: |
            HOST_UID=1001
            HOST_GID=1001
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-php:latest
          labels: ${{ steps.meta-php.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Extract Docker metadata for MariaDB
        id: meta-mariadb
        uses: docker/metadata-action@v4
        with:
          labels: |
            org.opencontainers.image.description=Docker image for MariaDB
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-mariadb
      - name: Build and push image for MariaDB
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: tools/docker/mariadb/build.Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-mariadb:latest
          labels: ${{ steps.meta-mariadb.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
